import { useEffect, useMemo, useState } from 'react'
import { Building2, Plus, Search, X, Save, Edit2, Trash2 } from 'lucide-react'
import { supabase, can, fetchAllRows } from '../lib/supabase.js'

const C={navy:'#022c22',white:'#fff',text:'#0f172a',muted:'#64748b',border:'#e5e7eb',green:'#10b981',greenBg:'#dcfce7',red:'#dc2626',redBg:'#fee2e2',amber:'#b45309',amberBg:'#fef3c7',grayBg:'#f1f5f9'}
const INP={width:'100%',padding:'10px 12px',border:'1px solid '+C.border,borderRadius:8,boxSizing:'border-box',fontSize:14,background:C.white,color:C.text}
const TIPOS=[['empresa_grupo','Empresa do grupo'],['cliente','Cliente'],['fornecedor','Fornecedor/prestador'],['parte_contraria','Parte contrária/reclamada'],['terceiro','Terceiro']]
const STATUS=[['ativo','Ativo'],['inativo','Inativo']]
function label(arr,v){return arr.find(x=>x[0]===v)?.[1]||v||'—'}
function F({label,children}){return <div style={{marginBottom:12}}><label style={{fontSize:11,fontWeight:800,color:C.muted,textTransform:'uppercase',display:'block',marginBottom:5}}>{label}</label>{children}</div>}
function Modal({title,onClose,children}){return <div onClick={e=>e.target===e.currentTarget&&onClose()} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',zIndex:500,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}><div style={{background:C.white,borderRadius:14,width:'100%',maxWidth:820,maxHeight:'92vh',display:'flex',flexDirection:'column',overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',padding:18,borderBottom:'1px solid '+C.border}}><b>{title}</b><button onClick={onClose} style={{border:0,background:'none',cursor:'pointer'}}><X/></button></div><div style={{padding:18,overflow:'auto'}}>{children}</div></div></div>}
function Chip({children,kind='green'}){const m={green:[C.greenBg,C.green],red:[C.redBg,C.red],amber:[C.amberBg,C.amber],gray:[C.grayBg,C.muted]};const [bg,color]=m[kind]||m.gray;return <span style={{fontSize:10,fontWeight:900,padding:'3px 8px',borderRadius:999,background:bg,color,textTransform:'uppercase',whiteSpace:'nowrap'}}>{children}</span>}

const empty={nome:'',nome_fantasia:'',cnpj:'',tipo:'parte_contraria',grupo_economico:'',email:'',telefone:'',contato_principal:'',endereco:'',observacoes:'',status:'ativo'}

export default function PartesCRM({profile}){
  const [partes,setPartes]=useState([]),[processos,setProcessos]=useState([]),[q,setQ]=useState(''),[tipo,setTipo]=useState('todos'),[modal,setModal]=useState(false),[form,setForm]=useState(empty),[loading,setLoading]=useState(true)
  const canEditPartes = can(profile, 'processos.editar')
  const load=async()=>{setLoading(true);const eid=profile.escritorio_id;const[p,proc]=await Promise.all([
    fetchAllRows(()=>supabase.from('partes_crm').select('*').eq('escritorio_id',eid).order('nome')),
    fetchAllRows(()=>supabase.from('processos').select('id,numero,titulo,parte_contraria_id,parte_contraria,status,categoria,valor_acao,valor_gasto,valor_economizado').eq('escritorio_id',eid))
  ]);setPartes(p||[]);setProcessos(proc||[]);setLoading(false)}
  useEffect(()=>{load()},[profile.escritorio_id])
  const filtradas=useMemo(()=>{const term=q.trim().toLowerCase();return partes.filter(p=>(tipo==='todos'||p.tipo===tipo)&&(!term||[p.nome,p.nome_fantasia,p.cnpj,p.grupo_economico,p.email,p.contato_principal].some(v=>String(v||'').toLowerCase().includes(term))))},[partes,q,tipo])
  const stats=(p)=>{const vinculados=processos.filter(x=>x.parte_contraria_id===p.id||(!x.parte_contraria_id&&x.parte_contraria===p.nome));const valorCausa=vinculados.reduce((s,x)=>s+Number(x.valor_acao||0),0);const gasto=vinculados.reduce((s,x)=>s+Number(x.valor_gasto||0),0);const economia=vinculados.reduce((s,x)=>s+Number(x.valor_economizado||0),0);return {qtd:vinculados.length,ativos:vinculados.filter(x=>x.status!=='encerrado').length,valorCausa,gasto,economia}}
  const open=(p=null)=>{if(!canEditPartes)return alert('Visitante possui acesso somente leitura.');setForm(p?{...empty,...p}:empty);setModal(true)}
  const save=async()=>{if(!canEditPartes)return alert('Visitante possui acesso somente leitura.');if(!form.nome.trim())return alert('Informe o nome da parte.');const payload={...form,nome:form.nome.trim(),escritorio_id:profile.escritorio_id,created_by:form.created_by||profile.id};const r=form.id?await supabase.from('partes_crm').update(payload).eq('id',form.id):await supabase.from('partes_crm').insert(payload);if(r.error)return alert(r.error.message);setModal(false);load()}
  const del=async(p)=>{if(!can(profile,'processos.editar'))return alert('Sem permissão.');const st=stats(p);if(st.qtd>0)return alert('Esta parte possui processos vinculados. Inative-a em vez de excluir.');if(confirm('Excluir esta parte do CRM?')){const {error}=await supabase.from('partes_crm').delete().eq('id',p.id);if(error)return alert(error.message);load()}}
  if(loading)return <div style={{padding:40,color:C.muted}}>Carregando partes...</div>
  return <div style={{padding:24}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h1 style={{margin:0,fontSize:22}}>Partes / CRM Jurídico</h1><p style={{color:C.muted,margin:'6px 0 0'}}>Empresas do grupo, clientes, fornecedores e partes contrárias recorrentes.</p></div>{can(profile,'processos.criar')&&<button onClick={()=>open()} style={{background:C.navy,color:'white',border:0,borderRadius:8,padding:'10px 16px',fontWeight:800,display:'flex',gap:8,alignItems:'center'}}><Plus size={16}/>Nova Parte</button>}</div>
    <div style={{display:'flex',gap:10,margin:'18px 0',flexWrap:'wrap'}}><div style={{position:'relative',flex:1,minWidth:260}}><Search size={15} style={{position:'absolute',left:10,top:13,color:C.muted}}/><input style={{...INP,paddingLeft:34}} placeholder="Buscar por nome, CNPJ, grupo, contato ou e-mail" value={q} onChange={e=>setQ(e.target.value)}/></div><select style={{...INP,width:240}} value={tipo} onChange={e=>setTipo(e.target.value)}><option value="todos">Todos os tipos</option>{TIPOS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12}}>{filtradas.map(p=>{const s=stats(p);return <div key={p.id} style={{background:C.white,border:'1px solid '+C.border,borderRadius:14,padding:16}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'start'}}><div style={{minWidth:0}}><div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:8}}><Chip>{label(TIPOS,p.tipo)}</Chip><Chip kind={p.status==='ativo'?'green':'gray'}>{label(STATUS,p.status)}</Chip></div><h3 style={{margin:'0 0 3px',fontSize:16,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{p.nome}</h3>{p.nome_fantasia&&<div style={{fontSize:12,color:C.muted}}>{p.nome_fantasia}</div>}<div style={{fontSize:12,color:C.muted,marginTop:4}}>{p.cnpj||'CNPJ não informado'}</div>{p.grupo_economico&&<div style={{fontSize:12,color:C.muted}}>Grupo: {p.grupo_economico}</div>}</div><div style={{display:'flex',gap:6}}>{canEditPartes&&<button onClick={()=>open(p)} style={{border:'1px solid '+C.border,background:C.white,borderRadius:8,padding:8,cursor:'pointer'}}><Edit2 size={14}/></button>}{canEditPartes&&<button onClick={()=>del(p)} style={{border:'1px solid '+C.border,background:C.white,color:C.red,borderRadius:8,padding:8,cursor:'pointer'}}><Trash2 size={14}/></button>}</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:14}}><div style={{background:C.grayBg,borderRadius:10,padding:8}}><b>{s.qtd}</b><div style={{fontSize:11,color:C.muted}}>processos</div></div><div style={{background:C.grayBg,borderRadius:10,padding:8}}><b>{s.ativos}</b><div style={{fontSize:11,color:C.muted}}>ativos</div></div><div style={{background:C.grayBg,borderRadius:10,padding:8}}><b>{s.economia.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b><div style={{fontSize:11,color:C.muted}}>economia</div></div></div>{(p.contato_principal||p.email||p.telefone)&&<div style={{borderTop:'1px solid '+C.border,marginTop:12,paddingTop:10,fontSize:12,color:C.muted}}>{p.contato_principal&&<div>Contato: {p.contato_principal}</div>}{p.email&&<div>E-mail: {p.email}</div>}{p.telefone&&<div>Telefone: {p.telefone}</div>}</div>}</div>})}</div>
    {!filtradas.length&&<div style={{background:C.white,border:'1px dashed '+C.border,borderRadius:12,padding:30,textAlign:'center',color:C.muted}}>Nenhuma parte encontrada.</div>}
    {modal&&<Modal title={form.id?'Editar parte':'Nova parte'} onClose={()=>setModal(false)}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><F label="Nome / razão social"><input style={INP} value={form.nome||''} onChange={e=>setForm({...form,nome:e.target.value})}/></F><F label="Nome fantasia"><input style={INP} value={form.nome_fantasia||''} onChange={e=>setForm({...form,nome_fantasia:e.target.value})}/></F><F label="CNPJ"><input style={INP} value={form.cnpj||''} onChange={e=>setForm({...form,cnpj:e.target.value})}/></F><F label="Tipo"><select style={INP} value={form.tipo||'parte_contraria'} onChange={e=>setForm({...form,tipo:e.target.value})}>{TIPOS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></F><F label="Grupo econômico"><input style={INP} value={form.grupo_economico||''} onChange={e=>setForm({...form,grupo_economico:e.target.value})}/></F><F label="Status"><select style={INP} value={form.status||'ativo'} onChange={e=>setForm({...form,status:e.target.value})}>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></F></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><F label="Contato principal"><input style={INP} value={form.contato_principal||''} onChange={e=>setForm({...form,contato_principal:e.target.value})}/></F><F label="E-mail"><input style={INP} value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></F><F label="Telefone"><input style={INP} value={form.telefone||''} onChange={e=>setForm({...form,telefone:e.target.value})}/></F></div><F label="Endereço"><input style={INP} value={form.endereco||''} onChange={e=>setForm({...form,endereco:e.target.value})}/></F><F label="Observações"><textarea style={{...INP,minHeight:90}} value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></F><button onClick={save} style={{background:C.navy,color:'white',border:0,borderRadius:8,padding:'11px 18px',fontWeight:800,display:'flex',gap:8,alignItems:'center'}}><Save size={16}/>Salvar</button></Modal>}
  </div>
}
